// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQbx4DGsqtAh38Je3Tl4ntHST4nxn5f_E',
    appId: '1:480177621362:web:dc92d7950ba43ba650b5eb',
    messagingSenderId: '480177621362',
    projectId: 'citasmedicasv4',
    authDomain: 'citasmedicasv4.firebaseapp.com',
    storageBucket: 'citasmedicasv4.appspot.com',
    measurementId: 'G-1L5DT3YYK4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjznPBksLa1DQm40AnWnu5PaB1oTQLQic',
    appId: '1:480177621362:android:104fee5c653660c550b5eb',
    messagingSenderId: '480177621362',
    projectId: 'citasmedicasv4',
    storageBucket: 'citasmedicasv4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAh4xckM5DX3uI5QObgzdlZiWJCwvmxclo',
    appId: '1:480177621362:ios:cbef6f35b569f8d750b5eb',
    messagingSenderId: '480177621362',
    projectId: 'citasmedicasv4',
    storageBucket: 'citasmedicasv4.appspot.com',
    iosBundleId: 'com.example.citasMedicav4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAh4xckM5DX3uI5QObgzdlZiWJCwvmxclo',
    appId: '1:480177621362:ios:3e4e7bdce960c95650b5eb',
    messagingSenderId: '480177621362',
    projectId: 'citasmedicasv4',
    storageBucket: 'citasmedicasv4.appspot.com',
    iosBundleId: 'com.example.citasMedicav4.RunnerTests',
  );
}
